name: Tristan Kirkpatrick
description: Blogging about Teaching, Gadgets and Anything EdTech
meta_description: "Blogging about Teaching, Gadgets and Anything EdTech"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://www.teachthemtocode.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'tristankirkpatrick'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Your Name'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
